language: objective-c

notifications:
  email: false

xcode_workspace: ZeroStore.xcworkspace
xcode_scheme: ZeroStore
osx_image: xcode7

script: ./xctool/xctool.sh -workspace ZeroStore.xcworkspace -scheme ZeroStoreTests clean test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination 'name=iPhone 6,OS=9.0'

before_install:
  - git clone https://github.com/facebook/xctool.git
  - gem install cocoapods -v '0.38.2'
