language: objective-c

notifications:
  email: false

xcode_workspace: ZeroStore.xcworkspace
xcode_scheme: ZeroStore
osx_image: xcode7

script: xctool -workspace ZeroStore.xcworkspace -scheme ZeroStore clean test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator

before_install:
  - gem install cocoapods -v '0.38.2'
